INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1234','John', 'Doe');
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1235','Jane', 'Doe' );
INSERT INTO ACCOUNT(ACCOUNTNUMBER, FIRSTNAME, SECONDNAME) VALUES('1236', 'Jim', 'Taylor');